[Tests-Only][CI] Update .drone.star file for new changes from activity app
owncloud/updater pull request #608
Opened 2021-07-05 05:07 UTC by dpakach

Related https://github.com/owncloud/QA/issues/678
- Fix code coverage reporting
- Implement early fail and full-ci in drone CI behavior like what is done in core and other repos

**note** this PR was generated by a automated script

2021-07-05 05:24 UTC, phil-davis requested changes

2021-07-05 05:24 UTC, phil-davis commented on .drone.star
> -	return codestyle() + jscodestyle() + phpstan() + phan() + phplint()
`phplint()` needs to be put back.

2021-07-07 06:25 UTC, dpakach commented on src/Tests/phpunit.xml
> +		<log type="coverage-clover" target="../../tests/output/clover.xml"/>
I had to change the coverage output path here so that it aligns with the standard .drone.star file format

cc @phil-davis

2021-07-07 06:52 UTC, phil-davis approved these changes

2021-07-07 06:55 UTC, phil-davis commented
Note: this is not a "real normal" oC10 app. But the `.drone.star` CI works OK in a way that the "app" code ends up in a `server/apps/updater` directory, and code analysis, unit tests etc run happily like that.

So that helps us use mostly common drone starlark code here.

2021-07-07 07:17 UTC, merged